# Project information
site_name: AmrPlusPlus 1.1 Docs

# Copyright
copyright: '&copy; Copyright 2019, Microbial Ecology Group.'

# Configuration 
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - header.autohide
    # Comment out the lines below to use default layout
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - attr_list  
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page Tree
nav:
  - 🔗 MEGARes: https://megares.meglab.org/
  - 🔗 Microbial Ecology Group: https://meg.colostate.edu/
  - Introduction: index.md
  - Example Analysis and Output: analysisoutput.md
  - Initial Setup:
    - Installation to Run AMR++: setup/installation.md
    - Import AMR++ Workflow: setup/import.md
  - Running AMR++:
    - Upload Data into AMR++: running/upload.md
    - Run AMR++ Workflow: running/runworkflow.md
  - AMR++ Documentation:
    - Pipeline Description: documentation/pipeline.md
    - User Manual (Options and Settings): documentation/usermanual.md
    - Docker Commands: documentation/docker.md
  - References: references.md
  - Citing AMR++: citing.md
  - Contact: contact.md

